### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by oliviertassinari** [oliviertassinari/react-conf-2024-pigment-css#1]
- [x] Add favicon to the presentation with Pigment CSS logo
- [x] Slide1.tsx, hardcode the values for the animation, once we find ones that work well
- [x] Load the right font
- [x] Set the right color palette

After talk

- [ ] Port the simplification of https://github.com/mui/pigment-css/blob/master/examples/pigment-css-vite-ts/src/App.tsx#L117-L121 to the repo

```jsx
import { styled, css } from '@pigment-css/react';

const Title = styled('h1')({
  fontFamily: 'Arial',
});

const Container = styled.div`
  font-size: 10px;
  border: 1px solid red;

  &:hover {
    border-color: blue;
  }

  ${Title} {
    margin-bottom: 24px;
  }
`;

export default function Modal() {
  return (
    <Container>
      <Title>Hello</Title>
      <span className={css({ position: 'absolute' })}>x</span>
      <div sx={{ py: 3 }}>
        Body
      </div>
    </Container>
  );
}
```
